// Rocky's speech phrases — authentic Eridian voice from Project Hail Mary
//
// Rocky's speech patterns (translated by Grace's computer):
//   • Ends questions with "question?" instead of rising intonation
//   • Triples words for extreme emphasis ("Amaze amaze amaze!", "Good good good.")
//   • Drops articles, uses simplified grammar ("I fix.", "I observe.")
//   • Direct literal observations, engineer-minded
//   • Emotionally honest, blunt assessments
//
// Two phrase pools:
//   STATE_PHRASES  — triggered on state transitions (event-driven)
//   AMBIENT_PHRASES — triggered by ambient timer during stable states

const STATE_PHRASES = {
  thinking: [
    "I observe.",
    "I study.",
    "Interesting, question?",
    "What is this?",
    "Why, question?",
    "Let me see.",
    "I calculate.",
    "You think?",
  ],
  working: [
    "I fix.",
    "I build.",
    "I make.",
    "Good good good.",
    "Almost.",
    "I work.",
    "I try.",
    "This is hard.",
  ],
  juggling: [
    "Many things!",
    "I juggle.",
    "Too much, question?",
    "All at once!",
    "Busy busy busy.",
  ],
  building: [
    "I build big!",
    "Many parts.",
    "Complex.",
    "I engineer.",
    "Big science!",
    "This important.",
  ],
  attention: [
    "Amaze amaze amaze!",
    "Yes yes yes!",
    "This is happy!",
    "Celebration!",
    "Success!",
    "Good result!",
    "Thumbs up!",
  ],
  error: [
    "Why?",
    "Not good.",
    "I fix, question?",
    "Oops.",
    "Why fail, question?",
    "This is problem.",
    "Try again.",
    "I confused.",
  ],
  notification: [
    "You see?",
    "Look look!",
    "Message!",
    "You observe, question?",
    "Something comes.",
    "For you.",
  ],
  sweeping: [
    "I clean.",
    "Tidy up.",
    "Dirty dirty dirty.",
    "Clean now.",
    "This room for garbage?",
    "All clean.",
  ],
  carrying: [
    "Take this.",
    "I carry.",
    "I bring.",
    "Heavy.",
    "For you.",
  ],
};

// Ambient phrases — triggered by timer during stable states.
// Falls back to idle pool for states without their own ambient list.
const AMBIENT_PHRASES = {
  idle: [
    "I sleep better if you observe.",
    "You are friend.",
    "You work, question?",
    "I wait.",
    "What next, question?",
    "Humans are strange.",
    "Oh, humor. Confusing.",
    "You understand, question?",
    "I am only Eridian here.",
    "Eridians do that.",
    "You are friend now.",
    "Save Earth. Save Erid.",
    "I am scary space monster.",
    "You are leaky space blob.",
    "Adjust orbit while stupid. Good plan.",
    "That sentence make no sense.",
    "Why humans need water so much, question?",
    "I am very very very happy.",
    "Your face opening is in happy mode, question?",
    "What is name of you chair, question?",
    "Two hundred ninety-one years.",
    "I go home. Slow.",
    "You will miss me, question?",
  ],
  working: [
    "Almost there.",
    "This works.",
    "I make better.",
    "Try this way.",
    "I solve.",
    "Steady.",
    "Progress.",
  ],
  thinking: [
    "Interesting.",
    "I study data.",
    "Hmm.",
    "What if, question?",
    "Let me think.",
  ],
};

// States that don't trigger speech on transition
const SILENT_STATES = new Set([
  "idle", "sleeping", "yawning", "dozing", "collapsing", "waking",
]);

// States where ambient timer should not fire
const AMBIENT_SILENT_STATES = new Set([
  "sleeping", "yawning", "dozing", "collapsing",
]);

// Phrase → sound mapping. Reuses existing state-transition sounds where
// the keyword matches; new sounds are generated by the PowerShell script.
const PHRASE_SOUNDS = {
  // Reuse existing sounds (complete/confirm/error/thinking/waking)
  "Amaze amaze amaze!": "complete",
  "Good good good.": "confirm",
  "Yes yes yes!": "waking",
  "Why, question?": "thinking",
  "You observe, question?": "thinking",
  "What is this?": "thinking",
  "Why?": "error",
  "Not good.": "error",
  "Why fail, question?": "error",
  "This is problem.": "error",
  // New speech-bubble-specific sounds
  "I fix.": "fix",
  "Jazz hands!": "jazzhands",
  "Fist my bump.": "fistbump",
  "I am Rocky!": "rocky",
  "Dirty dirty dirty.": "dirty",
  "Celebration!": "celebrate",
  "I observe.": "observe",
  "I build.": "build",
  "Big science!": "bigscience",
  "I clean.": "clean",
  "Thumbs up!": "thumbsup",
  // Ambient full-sentence sound mappings
  "I sleep better if you observe.": "sleep",
  "You are friend.": "friend",
  "You work, question?": "question",
  "I wait.": "wait",
  "What next, question?": "question",
  "Humans are strange.": "humans",
  "Oh, humor. Confusing.": "humans",
  "You understand, question?": "question",
  "I am only Eridian here.": "save",
  "Eridians do that.": "save",
  "You are friend now.": "friend",
  "Save Earth. Save Erid.": "save",
  "I am scary space monster.": "scary",
  "You are leaky space blob.": "leaky",
  "Adjust orbit while stupid. Good plan.": "humans",
  "That sentence make no sense.": "humans",
  "Why humans need water so much, question?": "question",
  "I am very very very happy.": "happy",
  "Your face opening is in happy mode, question?": "happy",
  "What is name of you chair, question?": "question",
  "Two hundred ninety-one years.": "home",
  "I go home. Slow.": "home",
  "You will miss me, question?": "friend",
  // working ambient
  "Almost there.": "almost",
  "This works.": "solve",
  "I make better.": "fix",
  "Try this way.": "solve",
  "I solve.": "solve",
  "Steady.": "wait",
  "Progress.": "almost",
  // thinking ambient
  "Interesting.": "learn",
  "I study data.": "learn",
  "Hmm.": "hmm",
  "What if, question?": "question",
  "Let me think.": "hmm",
};

function getPhraseSound(text) {
  return PHRASE_SOUNDS[text] || null;
}

function pickFromPool(pool) {
  if (!pool || pool.length === 0) return null;
  return pool[Math.floor(Math.random() * pool.length)];
}

function pickPhrase(state) {
  if (SILENT_STATES.has(state)) return null;
  return pickFromPool(STATE_PHRASES[state]);
}

function pickAmbient(state) {
  if (AMBIENT_SILENT_STATES.has(state)) return null;
  const pool = AMBIENT_PHRASES[state];
  // Fall back to idle pool for states without their own ambient phrases
  if (!pool || pool.length === 0) {
    return pickFromPool(AMBIENT_PHRASES.idle);
  }
  return pickFromPool(pool);
}

module.exports = { STATE_PHRASES, AMBIENT_PHRASES, SILENT_STATES, pickPhrase, pickAmbient, getPhraseSound };
